# Default nginx
FROM oven/bun:1.1.33-alpine AS builder
WORKDIR /app
COPY package.json bun.lockb ./
RUN ["bun", "i"]
COPY . .
RUN ["bunx", "--bun", "vite", "build", "--outDir", "dist"]

FROM nginx:1.27.2-bookworm AS final
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /etc/nginx/html/zero
# Final image size: 192MB
