FROM oven/bun:1.1.33-alpine AS builder
WORKDIR /app
COPY package.json bun.lockb ./
RUN ["bun", "i"]
COPY . .
RUN ["bunx", "--bun", "vite", "build", "--outDir", "dist"]

FROM nginx:mainline-alpine3.20-slim
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /etc/nginx/html/zero
# 12.1 MB
